// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "hotels": hotels Resource Client
//
// Command:
// $ goagen
// --design=goa/design
// --out=$(GOPATH)/src/hotels
// --version=v1.3.0

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// SearchHotelsPath computes a request path to the search action of hotels.
func SearchHotelsPath() string {

	return fmt.Sprintf("/hotel/search")
}

// Search hotels
func (c *Client) SearchHotels(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewSearchHotelsRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewSearchHotelsRequest create the request corresponding to the search action endpoint of the hotels resource.
func (c *Client) NewSearchHotelsRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
