// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "hotels": Application Contexts
//
// Command:
// $ goagen
// --design=goa/design
// --out=$(GOPATH)/src/hotels
// --version=v1.3.0

package app

import (
	"context"
	"net/http"

	"github.com/goadesign/goa"
)

// SearchHotelsContext provides the hotels search action context.
type SearchHotelsContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
}

// NewSearchHotelsContext parses the incoming request URL and body, performs validations and creates the
// context used by the hotels controller search action.
func NewSearchHotelsContext(ctx context.Context, r *http.Request, service *goa.Service) (*SearchHotelsContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := SearchHotelsContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *SearchHotelsContext) OK(r HotelCollection) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	if r == nil {
		r = HotelCollection{}
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// InternalServerError sends a HTTP response with status code 500.
func (ctx *SearchHotelsContext) InternalServerError(err error) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 500, goa.ErrInternal(err))
}
