// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "hotels": Application User Types
//
// Command:
// $ goagen
// --design=goa/design
// --out=$(GOPATH)/src/hotels
// --version=v1.3.0

package app
